# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11q2nG_H1weObEtH-kSIPvuCDspNcR6yR
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('train.csv')

# Basic Exploration
print("\n--- Data Info ---")
df.info()

print("\n--- Data Description ---")
print(df.describe())

print("\n--- Missing Values ---")
print(df.isnull().sum())

print("\n--- Value Counts: Survived ---")
print(df['Survived'].value_counts())

# Univariate Analysis
plt.figure(figsize=(10, 4))
sns.countplot(x='Survived', data=df)
plt.title('Survival Count')
plt.show()

plt.figure(figsize=(10, 4))
sns.histplot(df['Age'].dropna(), kde=True, bins=30)
plt.title('Age Distribution')
plt.show()

plt.figure(figsize=(10, 4))
sns.boxplot(x='Pclass', y='Age', data=df)
plt.title('Age Distribution by Passenger Class')
plt.show()

# Bivariate Analysis
plt.figure(figsize=(10, 4))
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title('Survival by Sex')
plt.show()

plt.figure(figsize=(10, 4))
sns.histplot(data=df, x='Fare', hue='Survived', bins=30, kde=True)
plt.title('Fare Distribution by Survival')
plt.show()

# Correlation Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# Pairplot (subset for clarity)
sns.pairplot(df[['Survived', 'Age', 'Fare', 'Pclass']].dropna(), hue='Survived')
plt.show()

"""# Summary of Insights:
1)Most females survived, most males didn't.

2)Younger passengers had slightly higher survival.

3)First class passengers had better survival rate.

4)Fare and Pclass correlate with survival.

5)Age has some outliers and skewness.

"""